# Generated by Django 4.2.29 on 2026-03-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('smile', 'Smiling Face'), ('text', 'Text Message'), ('image', 'Custom Image'), ('clear', 'Clear Screen')], default='smile', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Content displayed (text or image path)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Display Session',
                'verbose_name_plural': 'Display Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LCDConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('rotation', models.IntegerField(choices=[(0, '0 degrees'), (90, '90 degrees'), (180, '180 degrees'), (270, '270 degrees')], default=0, help_text='Display rotation')),
                ('backlight', models.IntegerField(default=100, help_text='Backlight brightness (0-100%)')),
                ('contrast', models.FloatField(default=1.0, help_text='Display contrast (0.5-2.0)')),
                ('show_smile_on_startup', models.BooleanField(default=True, help_text='Show smiling face on startup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LCD Configuration',
                'verbose_name_plural': 'LCD Configurations',
            },
        ),
    ]
