# Generated by Django 4.2.29 on 2026-03-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edupi_activity_timer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_type', models.CharField(choices=[('minute_of_silence', 'Minute of Silence'), ('break_time', 'Break Time'), ('activity', 'Activity'), ('custom', 'Custom')], default='activity', help_text='Type of timer preset', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Display name for this preset', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this preset')),
                ('duration_minutes', models.PositiveIntegerField(default=10, help_text='Default duration in minutes')),
                ('display_color', models.CharField(default='#3B82F6', help_text='Hex color for the preset button/display', max_length=7)),
                ('led_color_start', models.CharField(default='#00FF00', help_text='Hex color code for timer start', max_length=7)),
                ('led_color_warning', models.CharField(default='#FFFF00', help_text='Hex color code for warning state', max_length=7)),
                ('led_color_end', models.CharField(default='#FF0000', help_text='Hex color code for timer end', max_length=7)),
                ('enable_breathing', models.BooleanField(default=False, help_text='Enable breathing circle animation')),
                ('enable_ambient_sound', models.BooleanField(default=False, help_text='Play ambient background sound')),
                ('ambient_sound_type', models.CharField(blank=True, choices=[('nature', 'Nature Sounds'), ('white_noise', 'White Noise'), ('ocean', 'Ocean Waves'), ('rain', 'Rain')], help_text='Type of ambient sound', max_length=50)),
                ('announce_start', models.BooleanField(default=False, help_text='Announce start with TTS')),
                ('announce_end', models.BooleanField(default=False, help_text='Announce end with TTS')),
                ('start_message', models.CharField(blank=True, default='', help_text='Message to announce at start', max_length=200)),
                ('end_message', models.CharField(blank=True, default='', help_text='Message to announce at end', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this preset is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timer Preset',
                'verbose_name_plural': 'Timer Presets',
                'ordering': ['preset_type'],
            },
        ),
        migrations.AddField(
            model_name='timerconfig',
            name='display_color',
            field=models.CharField(default='#3B82F6', help_text='Hex color for display button', max_length=7),
        ),
        migrations.AddField(
            model_name='timerconfig',
            name='enable_ambient_sound',
            field=models.BooleanField(default=False, help_text='Play ambient background sound'),
        ),
        migrations.AddField(
            model_name='timerconfig',
            name='enable_breathing',
            field=models.BooleanField(default=False, help_text='Enable breathing circle animation'),
        ),
        migrations.AddField(
            model_name='timerconfig',
            name='preset',
            field=models.ForeignKey(blank=True, help_text='Base preset for this configuration (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs', to='edupi_activity_timer.timerpreset'),
        ),
    ]
