# Generated by Django 4.2.29 on 2026-03-29 09:33

from django.db import migrations, models
import django.db.models.deletion
import plugins.edupi.routines.models


class Migration(migrations.Migration):

    dependencies = [
        ('edupi_routines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenterbuttonmapping',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this mapping is active'),
        ),
        migrations.AlterField(
            model_name='presenterbuttonmapping',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use this as the default mapping'),
        ),
        migrations.AlterField(
            model_name='presenterbuttonmapping',
            name='name',
            field=models.CharField(default='Default', help_text='Name of this button mapping configuration', max_length=50),
        ),
        migrations.AlterField(
            model_name='presenterbuttonmapping',
            name='next_button_code',
            field=models.PositiveIntegerField(default=115, help_text='Event code for Next button'),
        ),
        migrations.AlterField(
            model_name='presenterbuttonmapping',
            name='play_pause_button_code',
            field=models.PositiveIntegerField(default=164, help_text='Event code for Play/Pause button'),
        ),
        migrations.AlterField(
            model_name='presenterbuttonmapping',
            name='prev_button_code',
            field=models.PositiveIntegerField(default=114, help_text='Event code for Previous button'),
        ),
        migrations.AlterField(
            model_name='presenterbuttonmapping',
            name='stop_button_code',
            field=models.PositiveIntegerField(default=116, help_text='Event code for Stop button'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload MP3/WAV file (optional, overrides TTS)', null=True, upload_to=plugins.edupi.routines.models.routine_audio_path),
        ),
        migrations.AlterField(
            model_name='routine',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this routine belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines', to='edupi_routines.routinecategory'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='content',
            field=models.TextField(help_text='Routine text content (one line per instruction)'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this routine is active'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='is_pre_built',
            field=models.BooleanField(default=False, help_text='Whether this is a built-in routine'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='title',
            field=models.CharField(help_text='Title of the routine', max_length=200),
        ),
        migrations.AlterField(
            model_name='routine',
            name='tts_engine',
            field=models.CharField(choices=[('pyttsx3', 'System TTS (Offline)'), ('edge_tts', 'Edge TTS (High Quality)'), ('gtts', 'Google TTS (Online)'), ('none', 'Use Uploaded Audio')], default='pyttsx3', help_text='Text-to-speech engine to use', max_length=20),
        ),
        migrations.AlterField(
            model_name='routine',
            name='tts_language',
            field=models.CharField(default='en', help_text="Language code (e.g., 'en', 'ro', 'es')", max_length=10),
        ),
        migrations.AlterField(
            model_name='routine',
            name='tts_speed',
            field=models.FloatField(default=1.0, help_text='TTS speed multiplier (0.5 = slow, 2.0 = fast)'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='tts_voice',
            field=models.CharField(blank=True, help_text='Voice name (engine-specific)', max_length=100),
        ),
        migrations.AlterField(
            model_name='routinecategory',
            name='category_type',
            field=models.CharField(choices=[('warm_up', 'Warm-up'), ('transition', 'Transition'), ('cooldown', 'Cooldown'), ('custom', 'Custom')], default='custom', help_text='Type of routine category', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='routinecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this category'),
        ),
        migrations.AlterField(
            model_name='routinecategory',
            name='display_color',
            field=models.CharField(default='#3B82F6', help_text='Hex color for this category', max_length=7),
        ),
        migrations.AlterField(
            model_name='routinecategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this category is active'),
        ),
        migrations.AlterField(
            model_name='routinecategory',
            name='name',
            field=models.CharField(help_text='Display name for this category', max_length=100),
        ),
        migrations.AlterField(
            model_name='routinecategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)'),
        ),
        migrations.AlterField(
            model_name='routinesession',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the routine completed', null=True),
        ),
        migrations.AlterField(
            model_name='routinesession',
            name='current_line_index',
            field=models.PositiveIntegerField(default=0, help_text='Current line being played (0-based)'),
        ),
        migrations.AlterField(
            model_name='routinesession',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='When the routine was last paused', null=True),
        ),
        migrations.AlterField(
            model_name='routinesession',
            name='routine',
            field=models.ForeignKey(help_text='Routine being played', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='edupi_routines.routine'),
        ),
        migrations.AlterField(
            model_name='routinesession',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the routine started', null=True),
        ),
        migrations.AlterField(
            model_name='routinesession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('playing', 'Playing'), ('paused', 'Paused'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='pending', help_text='Current playback status', max_length=20),
        ),
        migrations.AlterField(
            model_name='routinesession',
            name='total_duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Total duration in seconds', null=True),
        ),
    ]
