"""Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import logging
import os
import socket
import zoneinfo
from pathlib import Path

from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def discover_plugin_apps():
    """
    Auto-discover plugin apps in the plugins directory.

    This function scans the plugins directory for Django apps and
    returns a list of app paths that can be added to INSTALLED_APPS.
    """
    plugins_path = BASE_DIR / "plugins"
    plugin_apps = []

    if not plugins_path.exists():
        return plugin_apps

    for author_dir in plugins_path.iterdir():
        if not author_dir.is_dir():
            continue

        for plugin_dir in author_dir.iterdir():
            if not plugin_dir.is_dir():
                continue

            # Check if this is a Django app (has __init__.py)
            plugin_file = plugin_dir / "__init__.py"
            if plugin_file.exists():
                # Import path: plugins.author.plugin_name
                import_path = f"plugins.{author_dir.name}.{plugin_dir.name}"
                plugin_apps.append(import_path)

    return plugin_apps


# Auto-discover plugins at startup
AUTO_DISCOVERED_PLUGINS = discover_plugin_apps()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-7wbv0rx9-5e7qq+uusulib!mekrfo+qqfpynpsjlnjxi*@&=y_"
)

# SECURITY WARNING: don't with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "t", "yes")


def local_host_names() -> list[str]:
    """Names this machine can be reached by right now, without being told them.

    The installer bakes into `.env` the address it saw at install time, but the
    Pi takes its address over DHCP and moves. On the field Pi the file said
    `192.168.68.63` while the machine later came up on `.66`, so a teacher
    browsing the address they had been given got Django's 400 DisallowedHost —
    and the bare hostname (`tinko`), which is what the LCD and the setup portal
    display, was rejected the same way. Both are recorded facts about this
    machine that nothing ever revisits, so ask the machine instead.
    """
    names = {socket.gethostname()}
    # ".local" with the leading dot: Django reads that as "this domain and any
    # of its subdomains", which covers the mDNS name (tinko.local) however the
    # hostname itself changes.
    names.add(".local")

    # The address of the interface that would carry traffic off the Pi. A UDP
    # connect sends no packets, so this needs no network and no DNS and nothing
    # leaves the machine; with no route at all it raises, and the names above
    # still apply.
    probe = None
    try:
        probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        probe.connect(("192.0.2.1", 9))  # TEST-NET-1: reserved, never routed
        names.add(probe.getsockname()[0])
    except OSError:
        pass
    finally:
        if probe is not None:
            probe.close()

    return sorted(names)


def allowed_hosts(configured: str) -> list[str]:
    """Merge the configured host list with the names this machine answers to.

    `configured` is the raw `ALLOWED_HOSTS` environment value, comma separated.
    """
    hosts = [host.strip() for host in configured.split(",") if host.strip()]
    if not hosts:
        # `ALLOWED_HOSTS = []` with DEBUG off rejects every request, including
        # the dashboard on the Pi's own screen. Keep the loopback names.
        hosts = ["localhost", "127.0.0.1", "0.0.0.0"]

    return sorted(set(hosts) | set(local_host_names()))


ALLOWED_HOSTS = allowed_hosts(os.environ.get("ALLOWED_HOSTS", ""))


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "core.edupi_core",
    "core.plugin_system",
    "core.update_system",
    # Core plugins (loaded before auto-discovered plugins)
    "plugins.edupi.activity_timer",
    "plugins.edupi.touch_piano",
    "plugins.edupi.noise_monitor",
    "plugins.edupi.routines",
] + AUTO_DISCOVERED_PLUGINS

# Remove duplicates while preserving order
seen = set()
INSTALLED_APPS = [x for x in INSTALLED_APPS if not (x in seen or seen.add(x))]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "core.edupi_core.context_processors.site_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Channels configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


def set_sqlite_pragmas(sender, connection, **kwargs):
    """Set SQLite PRAGMAs to reduce SD card writes on Raspberry Pi."""
    if connection.vendor == "sqlite":
        cursor = connection.cursor()
        cursor.execute("PRAGMA temp_store=MEMORY")
        cursor.execute("PRAGMA synchronous=NORMAL")


from django.db.backends.signals import connection_created

connection_created.connect(set_sqlite_pragmas)

# Use local memory for caching
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Store sessions in the cache instead of the SQLite database
SESSION_ENGINE = "django.contrib.sessions.backends.cache"


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# Where the machine's own zone is named. Constants because the tests build a
# throwaway tree instead of reading the host's /etc.
TIME_ZONE_FILE = "/etc/timezone"
LOCALTIME_FILE = "/etc/localtime"
ZONEINFO_ROOT = "/usr/share/zoneinfo/"


def valid_time_zone(name: str | None) -> str | None:
    """`name` if this system can resolve it as a time zone, else None.

    Both halves matter. The name comes from a file or a symlink (see below), and
    a value Django cannot resolve is not a cosmetic problem: it raises the moment
    it converts a time, so a typo would take pages down instead of showing a
    wrong hour. Rejecting absolute paths and `..` keeps a strange file from
    naming a zone outside the zoneinfo tree.
    """
    candidate = (name or "").strip()
    if not candidate or candidate.startswith("/") or ".." in candidate:
        return None
    try:
        zoneinfo.ZoneInfo(candidate)
    except (ValueError, KeyError, OSError):
        # KeyError covers ZoneInfoNotFoundError (no such zone, or no tzdata on
        # the machine at all), ValueError a malformed key.
        return None
    return candidate


def system_time_zone() -> str | None:
    """The zone this machine is set to, or None if it cannot be named."""
    # Debian and Raspberry Pi OS keep the name in a file ...
    try:
        name = Path(TIME_ZONE_FILE).read_text(encoding="utf-8").strip()
    except OSError:
        name = ""
    if valid_time_zone(name):
        return name

    # ... and everywhere else /etc/localtime is a symlink into the zoneinfo
    # tree, whose path *is* the name (`.../zoneinfo/Europe/Bucharest`).
    try:
        # `as_posix()` because Windows resolves to backslashes, and the root
        # below is compared against with forward slashes on every platform.
        target = Path(LOCALTIME_FILE).resolve().as_posix()
    except OSError:
        return None
    if ZONEINFO_ROOT in target:
        return valid_time_zone(target.split(ZONEINFO_ROOT, 1)[1])
    return None


def time_zone(default: str = "UTC") -> str:
    """The zone times are shown and stored in.

    The machine's own zone wins, because that is what `date` prints, what the
    LCD and every other clock in the room show, and what NTP keeps correct:
    move the Pi with `timedatectl set-timezone` and the dashboard follows on the
    next restart. `TIME_ZONE` in `.env` — which `install-raspberry-pi.sh` writes
    from the machine's zone at install time — is the fallback for platforms with
    no system zone (Windows, a container), and UTC the last resort.

    This order is deliberate: the field Pi had `Europe/Bucharest` in `.env` and
    `TIME_ZONE = "UTC"` hardcoded here, so every time the app showed was three
    hours behind the wall clock (`datetime.now()`, template `|date` and the
    noise chart's clock labels alike, since Django also exports this setting as
    the process's `TZ`). Honouring the configured value alone would have fixed
    that one Pi while leaving the app pinned to a zone the machine may later
    leave.
    """
    return system_time_zone() or valid_time_zone(os.environ.get("TIME_ZONE")) or default


TIME_ZONE = time_zone()

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Login redirect URL
LOGIN_REDIRECT_URL = "/"

# Locale paths
LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# Ensure logs directory exists
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": str(LOGS_DIR / "django.log"),
            "formatter": "verbose",
            "delay": True,  # Delay opening file until first log
        },
        "lcd_file": {
            "class": "logging.FileHandler",
            "filename": str(LOGS_DIR / "lcd_display.log"),
            "formatter": "verbose",
            "delay": True,  # Delay opening file until first log
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "plugins.edupi.lcd_display": {
            "handlers": ["console", "lcd_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "plugins.edupi.lcd_display.lcd_service": {
            "handlers": ["console", "lcd_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
