"""Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import logging
import os
from pathlib import Path

from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def discover_plugin_apps():
    """
    Auto-discover plugin apps in the plugins directory.

    This function scans the plugins directory for Django apps and
    returns a list of app paths that can be added to INSTALLED_APPS.
    """
    plugins_path = BASE_DIR / "plugins"
    plugin_apps = []

    if not plugins_path.exists():
        return plugin_apps

    for author_dir in plugins_path.iterdir():
        if not author_dir.is_dir():
            continue

        for plugin_dir in author_dir.iterdir():
            if not plugin_dir.is_dir():
                continue

            # Check if this is a Django app (has __init__.py)
            plugin_file = plugin_dir / "__init__.py"
            if plugin_file.exists():
                # Import path: plugins.author.plugin_name
                import_path = f"plugins.{author_dir.name}.{plugin_dir.name}"
                plugin_apps.append(import_path)

    return plugin_apps


# Auto-discover plugins at startup
AUTO_DISCOVERED_PLUGINS = discover_plugin_apps()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-7wbv0rx9-5e7qq+uusulib!mekrfo+qqfpynpsjlnjxi*@&=y_"
)

# SECURITY WARNING: don't with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "t", "yes")

# Parse ALLOWED_HOSTS from environment variable
_allowed_hosts = os.environ.get("ALLOWED_HOSTS", "")
if _allowed_hosts:
    ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts.split(",") if host.strip()]
else:
    ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "core.edupi_core",
    "core.plugin_system",
    "core.update_system",
    # Core plugins (loaded before auto-discovered plugins)
    "plugins.edupi.activity_timer",
    "plugins.edupi.touch_piano",
    "plugins.edupi.noise_monitor",
    "plugins.edupi.routines",
] + AUTO_DISCOVERED_PLUGINS

# Remove duplicates while preserving order
seen = set()
INSTALLED_APPS = [x for x in INSTALLED_APPS if not (x in seen or seen.add(x))]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "core.edupi_core.context_processors.site_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Channels configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Login redirect URL
LOGIN_REDIRECT_URL = "/"

# Locale paths
LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# Ensure logs directory exists
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": str(LOGS_DIR / "django.log"),
            "formatter": "verbose",
            "delay": True,  # Delay opening file until first log
        },
        "lcd_file": {
            "class": "logging.FileHandler",
            "filename": str(LOGS_DIR / "lcd_display.log"),
            "formatter": "verbose",
            "delay": True,  # Delay opening file until first log
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "plugins.edupi.lcd_display": {
            "handlers": ["console", "lcd_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "plugins.edupi.lcd_display.lcd_service": {
            "handlers": ["console", "lcd_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
