# Generated by Django 4.2.29 on 2026-03-27 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseMonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Configuration', help_text='Name of this configuration', max_length=100)),
                ('instant_window_seconds', models.PositiveIntegerField(default=10, help_text='Window size for instant average in seconds')),
                ('session_window_minutes', models.PositiveIntegerField(default=5, help_text='Window size for session average in minutes')),
                ('led_brightness', models.PositiveIntegerField(default=100, help_text='LED brightness percentage (10-100)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('is_default', models.BooleanField(default=False, help_text='Use this as the default configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Noise Monitor Configuration',
                'verbose_name_plural': 'Noise Monitor Configurations',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoiseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('test', 'Test - Silent Mode'), ('teaching', 'Teaching - Moderate Noise'), ('group_work', 'Group Work - Higher Tolerance'), ('custom', 'Custom - User Defined')], default='teaching', help_text='Type of noise profile', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name for this profile', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this profile')),
                ('yellow_threshold', models.PositiveIntegerField(default=40, help_text='Noise level above which LED turns yellow (0-100)')),
                ('red_threshold', models.PositiveIntegerField(default=70, help_text='Noise level above which LED turns red (0-100)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this profile is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Noise Profile',
                'verbose_name_plural': 'Noise Profiles',
                'ordering': ['profile_type'],
            },
        ),
        migrations.CreateModel(
            name='NoiseReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_level', models.PositiveIntegerField(help_text='Raw noise level (0-100)')),
                ('instant_average', models.PositiveIntegerField(help_text='Instant average noise level (0-100)')),
                ('session_average', models.PositiveIntegerField(blank=True, help_text='Session average noise level (0-100)', null=True)),
                ('instant_color', models.CharField(default='green', help_text='Color of instant LED (green/yellow/red)', max_length=10)),
                ('session_color', models.CharField(default='green', help_text='Color of session LED (green/yellow/red)', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this reading was taken')),
                ('config', models.ForeignKey(help_text='Configuration during this reading', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='edupi_noise_monitor.noisemonitorconfig')),
            ],
            options={
                'verbose_name': 'Noise Reading',
                'verbose_name_plural': 'Noise Readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='noisemonitorconfig',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Noise profile to use', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs', to='edupi_noise_monitor.noiseprofile'),
        ),
    ]
