# Generated by Django 4.2.29 on 2026-04-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupi_noise_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noisemonitorconfig',
            name='audio_input_device',
            field=models.CharField(blank=True, default='', help_text='Name of the selected audio input device', max_length=255),
        ),
        migrations.AddField(
            model_name='noisemonitorconfig',
            name='audio_input_device_index',
            field=models.IntegerField(blank=True, help_text='System index of the audio input device', null=True),
        ),
    ]
