# Generated by Django 4.2.29 on 2026-03-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_path', models.CharField(help_text="Python import path (e.g., 'plugins.acme.myplugin')", max_length=255, unique=True)),
                ('name', models.CharField(help_text='Plugin display name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Plugin description')),
                ('author', models.CharField(blank=True, help_text='Plugin author', max_length=100)),
                ('version', models.CharField(help_text='Plugin version', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether the plugin is currently enabled')),
                ('is_installed', models.BooleanField(default=True, help_text='Whether the plugin is installed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the plugin was first discovered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the plugin was last updated')),
                ('last_enabled_at', models.DateTimeField(blank=True, help_text='When the plugin was last enabled', null=True)),
            ],
            options={
                'verbose_name': 'Plugin Status',
                'verbose_name_plural': 'Plugin Statuses',
                'ordering': ['-is_enabled', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PluginEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text="Event name (e.g., 'boot', 'register', 'error')", max_length=100)),
                ('message', models.TextField(blank=True, help_text='Event message or details')),
                ('data', models.TextField(blank=True, help_text='Additional event data (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plugin_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='plugin_system.pluginstatus')),
            ],
            options={
                'verbose_name': 'Plugin Event Log',
                'verbose_name_plural': 'Plugin Event Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PluginDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether this dependency is optional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='plugin_system.pluginstatus')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='plugin_system.pluginstatus')),
            ],
            options={
                'verbose_name': 'Plugin Dependency',
                'verbose_name_plural': 'Plugin Dependencies',
                'unique_together': {('plugin', 'depends_on')},
            },
        ),
        migrations.CreateModel(
            name='PluginConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuration key', max_length=100)),
                ('value', models.TextField(blank=True, help_text='Configuration value (JSON encoded)')),
                ('description', models.TextField(blank=True, help_text='Configuration description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plugin_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='plugin_system.pluginstatus')),
            ],
            options={
                'verbose_name': 'Plugin Configuration',
                'verbose_name_plural': 'Plugin Configurations',
                'ordering': ['key'],
                'unique_together': {('plugin_status', 'key')},
            },
        ),
        migrations.CreateModel(
            name='GPIOPinAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.PositiveSmallIntegerField(help_text='BCM GPIO pin number (0-27)')),
                ('pin_name', models.CharField(help_text='Logical name for this pin in the plugin', max_length=50)),
                ('purpose', models.CharField(blank=True, help_text='Description of what this pin is used for', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this allocation is currently active')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('plugin_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpio_pins', to='plugin_system.pluginstatus')),
            ],
            options={
                'verbose_name': 'GPIO Pin Allocation',
                'verbose_name_plural': 'GPIO Pin Allocations',
                'ordering': ['pin_number'],
                'unique_together': {('pin_number', 'is_active')},
            },
        ),
    ]
